baseURL = 'https://acj81.github.io/'
languageCode = 'en-uk'
title = 'Home'
theme = 'PaperMod'

[params]
  author = 'Anthony Jones'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

